In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [4]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [5]:
df = pd.read_excel("/content/drive/MyDrive/Sapphire IQ/Amazon Sales Data India.xlsx")

In [6]:
df.head()

,Order_ID,Order_Date,Category,Product,Quantity,Unit_Price_INR,Discount_Pct,Total_Sales_INR,Profit_INR,Payment_Method,Fulfillment,Order_Status,Ship_State
0,IN-AMD-100000,2024-04-12,Apparel & Fashion,Saree with Unstitched Blouse,3,1129.14,0.25,2540.56,702.96,Cash on Delivery (COD),Seller Flex,Delivered,Telangana
1,IN-AMD-100001,2025-03-11,Apparel & Fashion,Men Denim Jeans,3,1159.01,0.05,3303.18,770.96,UPI,Amazon (FBA),Shipped,Kerala
2,IN-AMD-100002,2026-05-10,Beauty & Personal Care,Ubtan Face Wash,1,287.77,0.00,287.77,86.73,UPI,Amazon (FBA),Delivered,West Bengal
3,IN-AMD-100003,2024-09-27,Electronics & Mobiles,Wireless Earbuds,4,20928.14,0.05,79526.93,26466.63,Credit/Debit Card,Amazon (FBA),Shipped,Rajasthan
4,IN-AMD-100004,2024-04-16,Beauty & Personal Care,Sunscreen Gel SPF 50,1,931.65,0.15,791.90,217.90,UPI,Seller Flex,Delivered,Karnataka

In [7]:
df.describe()

,Quantity,Unit_Price_INR,Discount_Pct,Total_Sales_INR,Profit_INR
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2.492600,6821.399659,0.085575,15578.989389,3316.700849
std,1.110076,9183.501994,0.076172,24159.351687,5805.862200
min,1.000000,150.270000,0.000000,118.820000,0.000000
25%,2.000000,1002.822500,0.000000,1931.245000,299.325000
50%,2.000000,2290.080000,0.100000,4795.800000,891.625000
75%,3.000000,7628.625000,0.150000,17357.332500,3250.530000
max,4.000000,34992.800000,0.250000,139647.920000,45596.300000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         10000 non-null  object
 1   Order_Date       10000 non-null  object
 2   Category         10000 non-null  object
 3   Product          10000 non-null  object
 4   Quantity         10000 non-null  int64
 5   Unit_Price_INR   10000 non-null  float64
 6   Discount_Pct     10000 non-null  float64
 7   Total_Sales_INR  10000 non-null  float64
 8   Profit_INR       10000 non-null  float64
 9   Payment_Method   10000 non-null  object
 10  Fulfillment      10000 non-null  object
 11  Order_Status     10000 non-null  object
 12  Ship_State       10000 non-null  object
dtypes: float64(4), int64(1), object(8)
memory usage: 1015.8+ KB

In [10]:
df.isnull().sum()

Order_ID           0
Order_Date         0
Category           0
Product            0
Quantity           0
Unit_Price_INR     0
Discount_Pct       0
Total_Sales_INR    0
Profit_INR         0
Payment_Method     0
Fulfillment        0
Order_Status       0
Ship_State         0
dtype: int64

In [13]:
df.shape

(10000, 17)

In [17]:
df.nunique()

Order_ID           10000
Order_Date           973
Category               5
Product               25
Quantity               4
Unit_Price_INR      9948
Discount_Pct           6
Total_Sales_INR     9966
Profit_INR          8892
Payment_Method         5
Fulfillment            3
Order_Status           4
Ship_State            10
Year                   3
Month                 12
Month_Name            12
Year_Month            32
dtype: int64

# **1. Overall Sales & Profit Performance**

In [16]:
total_sales = df["Total_Sales_INR"].sum()
total_profit = df["Profit_INR"].sum()
total_orders = df["Order_ID"].nunique()
total_units = df["Quantity"].sum()

average_order_value = (total_sales / total_orders if total_orders else 0 )

profit_margin = (total_profit / total_sales * 100 if total_sales else 0)

print("========== AMAZON INDIA KPIs ==========")
print(f"Total Sales       : ₹{total_sales:,.2f}")
print(f"Total Profit      : ₹{total_profit:,.2f}")
print(f"Total Orders      : {total_orders:,}")
print(f"Total Units Sold  : {total_units:,}")
print(f"Average Order Value: ₹{average_order_value:,.2f}")
print(f"Profit Margin     : {profit_margin:.2f}%")

========== AMAZON INDIA KPIs ==========
Total Sales       : ₹155,789,893.89
Total Profit      : ₹33,167,008.49
Total Orders      : 10,000
Total Units Sold  : 24,926
Average Order Value: ₹15,578.99
Profit Margin     : 21.29%

In [19]:
monthly = (
df.groupby("Year_Month")
    .agg(
        Sales=("Total_Sales_INR", "sum"),
        Profit=("Profit_INR", "sum"),
        Orders=("Order_ID", "nunique")
    )
    .reset_index()
    .sort_values("Year_Month")
)

display(monthly.head(10))

  Year_Month       Sales      Profit  Orders
0    2024-01  4441265.57  1016530.29     316
1    2024-02  4071073.66   778165.74     265
2    2024-03  5761054.84  1243584.05     310
3    2024-04  4612546.48  1041978.73     326
4    2024-05  4660178.05  1020331.21     324
5    2024-06  4810938.17   937123.34     311
6    2024-07  5744760.13  1256434.89     328
7    2024-08  4760372.35   976600.73     315
8    2024-09  4033814.56   914060.89     303
9    2024-10  4820971.84  1033414.57     311

# **The monthly sales and profit trend**

In [59]:
fig = px.line(monthly, x="Year_Month", y=["Sales", "Profit"], title="Monthly Sales & Profit", markers=True)
fig.show()

In [25]:
category_summary = (
    df.groupby("Category")
    .agg(
        Sales=("Total_Sales_INR", "sum"),
        Profit=("Profit_INR", "sum"),
        Units_Sold=("Quantity", "sum"),
        Orders=("Order_ID", "nunique")
    )
    .reset_index()
    .sort_values("Sales", ascending=False)
)

display(category_summary.round(2))

                 Category         Sales       Profit  Units_Sold  Orders
2   Electronics & Mobiles  1.235695e+08  26310257.24        7579    3045
3          Home & Kitchen  1.797322e+07   3837268.36        4684    1888
0       Apparel & Fashion  9.831025e+06   2085354.00        6452    2580
1  Beauty & Personal Care  2.889178e+06    604390.41        3734    1499
4      Pantry & Groceries  1.526964e+06    329738.48        2477     988

# **2.Category & Product Performance**

## **Category-wise Sales**

In [62]:
fig = px.bar(category_summary, x="Sales", y="Category", title="Category-wise Sales")
labels={"Sales": "Sales (₹)", "Category": "Category"}
fig.show()

##  **Category-wise Profit**

In [56]:
fig=px.bar (category_summary, x="Profit", y="Category", title="Category-wise Profit", orientation="h",  text_auto=".2s",)
labels={"Sales": "Profit (₹)", "Category": "Category"}
fig.show()

## **Category-wise Units Sold**

In [55]:
fig=px.bar(category_summary, x="Units_Sold", y="Category", title="Category-wise Units Sold", orientation="h",  text_auto=".2s",)
labels={"Sales": "Units Sold", "Category": "Category"}
fig.show()

In [47]:
top_10_products = (
    df.groupby("Product", as_index=False)
    .agg(
        Sales=("Total_Sales_INR", "sum"),
        Profit=("Profit_INR", "sum"),
        Units_Sold=("Quantity", "sum")
    )
    .sort_values("Sales", ascending=False)
    .head(10)
)

display(top_10_products.round(2))

                       Product        Sales      Profit  Units_Sold
10             Laptop Backpack  26529187.41  5628644.03        1641
15         Power Bank 20000mAh  25548449.07  5496680.51        1573
0                5G Smartphone  24330766.23  5109132.92        1478
24            Wireless Earbuds  23848640.89  5204191.90        1475
18                  Smartwatch  23312463.47  4871607.88        1412
20  Stainless Steel Dinner Set   3865114.25   819333.80         953
4       Cotton Bedsheet Double   3789133.82   843105.06         998
23              Water Purifier   3785924.80   794225.82         992
9            Induction Cooktop   3510999.56   761204.61         907
13          Mixer Grinder 750W   3022046.50   619399.07         834

## **Top 10 Products by Sales**

In [54]:
fig = px.bar(top_10_products, x="Sales", y="Product", title="Top 10 Products by Sales", orientation="h",  text_auto=".2s")
labels={"Sales": "Sales (₹)", "Product": "Product"}
fig.show()

# **3. Order Status & Revenue Loss**

In [63]:
print(df["Order_Status"].value_counts())

Order_Status
Delivered    8147
Shipped       868
Cancelled     500
Returned      485
Name: count, dtype: int64

In [64]:
status_summary = df.groupby("Order_Status").agg(
    Orders=("Order_ID", "nunique"),
    Sales=("Total_Sales_INR", "sum"),
    Profit=("Profit_INR", "sum")
).reset_index()

status_summary["Order_Percentage"] = status_summary["Orders"] / total_orders * 100

display(status_summary.round(2))

  Order_Status  Orders         Sales       Profit  Order_Percentage
0    Cancelled     500  7.688159e+06         0.00              5.00
1    Delivered    8147  1.258942e+08  29697472.88             81.47
2     Returned     485  7.960583e+06         0.00              4.85
3      Shipped     868  1.424694e+07   3469535.61              8.68

In [65]:
status = df["Order_Status"].str.strip().str.lower()

returned = df.loc[status == "returned", "Order_ID"].nunique()
cancelled = df.loc[status == "cancelled", "Order_ID"].nunique()

return_rate = returned / total_orders * 100
cancel_rate = cancelled / total_orders * 100

print(f"Returned Orders: {returned}")
print(f"Cancelled Orders: {cancelled}")
print(f"Return Rate: {return_rate:.2f}%")
print(f"Cancellation Rate: {cancel_rate:.2f}%")

Returned Orders: 485
Cancelled Orders: 500
Return Rate: 4.85%
Cancellation Rate: 5.00%

## **Order Status Overview**

In [67]:
fig = px.bar(status_summary, x="Order_Status", y="Orders",
             color="Order_Status", title="Order Status Overview",
             text="Orders")
fig.update_layout(template="plotly_white", showlegend=False)
fig.show()

## **Category-wise Returns & Cancellations**

In [69]:
category_status = df.assign(Status_Clean=status).groupby(
    ["Category", "Status_Clean"]
).agg(Orders=("Order_ID", "nunique")).reset_index()

loss_status = category_status[
    category_status["Status_Clean"].isin(["returned", "cancelled"]
)]

fig = px.bar(loss_status, x="Category", y="Orders",
             color="Status_Clean", barmode="group",
             title="Category-wise Returns & Cancellations",
             text_auto=True)
fig.show()

# **4. Payment, Fulfillment & Geographic Performance**

In [70]:
payment_summary = (
    df.groupby("Payment_Method")
    .agg(
        Sales=("Total_Sales_INR", "sum"),
        Profit=("Profit_INR", "sum"),
        Orders=("Order_ID", "nunique")
    )
    .reset_index()
    .sort_values("Sales", ascending=False)
)

display(payment_summary.round(2))

           Payment_Method        Sales       Profit  Orders
4                     UPI  78515436.26  16653494.14    4972
2       Credit/Debit Card  31069230.90   6525646.17    2074
1  Cash on Delivery (COD)  23101583.64   5008107.37    1458
3             Net Banking  15419486.46   3292296.82    1024
0        Amazon Pay Later   7684156.63   1687463.99     472

## **Sales by Payment Method**

In [98]:
fig= px.bar(payment_summary, x="Sales", y="Payment_Method", title="Sales by Payment Method", orientation="h",  text_auto=".2s")
fig.show()

## **Profit by Payment Method**

In [77]:
fig = px.bar(payment_summary, x="Profit", y="Payment_Method", title="Profit by Payment Method", orientation="h",  text_auto=".2s")
fig.show()

In [78]:
fulfillment_summary = (
    df.groupby("Fulfillment")
    .agg(
        Sales=("Total_Sales_INR", "sum"),
        Profit=("Profit_INR", "sum"),
        Orders=("Order_ID", "nunique"),
        Units_Sold=("Quantity", "sum")
    )
    .reset_index()
    .sort_values("Sales", ascending=False)
)

display(fulfillment_summary.round(2))

      Fulfillment         Sales       Profit  Orders  Units_Sold
0    Amazon (FBA)  1.075283e+08  22882414.52    7054       17540
2     Seller Flex  3.119839e+07   6815054.52    1966        4902
1  Merchant (FBM)  1.706321e+07   3469539.45     980        2484

## **Sales by Fulfilment Method**

In [86]:
fig = px.bar(fulfillment_summary, x="Sales", y="Fulfillment", title="Sales by Fulfilment Method", orientation="h",  text_auto=".2s")
fig.show()

## **Profit by Fulfilment Method**

In [88]:
fig = px.bar(fulfillment_summary, x="Profit", y="Fulfillment", title="Profit by Fulfilment Method", orientation="h",  text_auto=".2s")
fig.show()

In [89]:
state_summary = (
    df.groupby("Ship_State")
    .agg(
        Sales=("Total_Sales_INR", "sum"),
        Profit=("Profit_INR", "sum"),
        Orders=("Order_ID", "nunique"),
        Units_Sold=("Quantity", "sum")
    )
    .reset_index()
    .sort_values("Sales", ascending=False)
)

display(state_summary.round(2))

      Ship_State        Sales      Profit  Orders  Units_Sold
4    Maharashtra  29554237.21  6301731.56    1840        4585
2      Karnataka  24415704.16  5273235.35    1515        3765
0          Delhi  22361687.04  4699095.38    1444        3610
6     Tamil Nadu  17889855.25  3856864.11    1109        2785
8  Uttar Pradesh  14140675.36  2978266.81     991        2486
7      Telangana  13961458.53  2944127.16     906        2272
9    West Bengal  10864550.51  2344788.08     665        1645
1        Gujarat   9369304.18  2008021.80     591        1484
5      Rajasthan   6620697.25  1383028.68     456        1144
3         Kerala   6611724.40  1377849.56     483        1150

## **Top 15 State by Sales**

In [97]:
fig = px.bar(state_summary.head(15).sort_values("Sales"), x="Sales", y="Ship_State", title="Top 15 State by Sales", orientation="h",  text_auto=".2s")
fig.show()

## **Top 15 State by Profit**

In [96]:
fig= px.bar(state_summary.head(15).sort_values("Profit"), x="Profit", y="Ship_State", title="Top 15 State by Profit", orientation="h",  text_auto=".2s")
fig.show()

In [100]:
fig = px.bar(state_summary.nlargest(15, "Orders").sort_values("Orders"),
             x="Orders", y="Ship_State", orientation="h",
             title="Top 15 States by Orders", text_auto=True)
fig.show()